### ISSUE TITLE
Error deploying the app

### ISSUE THREAD

**Issue by adrianlzt** [rbbydotdev/someday#1]
I had this error (there were more `Cannot find...`):

```bash
❯ npm run deploy

> someday@1.0.0 deploy
> ./deploy.sh

Building backend...
~/Documentos/escalada/frontend-entrenamiento/someday/backend ~/Documentos/escalada/frontend-entrenamiento/someday

> backend@1.0.0 build
> tsc

src/app.ts:17:19 - error TS2503: Cannot find namespace 'GoogleAppsScript'.

17 function doGet(): GoogleAppsScript.HTML.HtmlOutput {
```

Fixed running a `npm i` in the `backend/` directory.

**Comment by adrianlzt** [comment]
The build script also misses a `mkdir dist`. It assumes it exists.

**Comment by rbbydotdev** [comment]
Hey these are great thanks for contributing! I've updated the build script for npm install if node_modules doesn't exist and and mkdir -p dist
