### ISSUE TITLE
[Packaging] Podman/Docker image

### ISSUE THREAD

**Issue by HarshDodiya1** [rbbydotdev/someday#4]
It would be nice to have an easily deployable Podman/Docker Image, containerized from the rest of the system.

**Comment by rbbydotdev** [comment]
That's a good point! I am imagining Someday V2 will have an additional option to self-host as simply as possible via a podman/Docker image. For now I think the major appeal is that self hosting is not required and you can host on google apps scripts **for free**

I have included a simple html example to show how you can [serve it within an iframe](https://github.com/rbbydotdev/someday?tab=readme-ov-file#self-host-iframe-html--remove-google-app-scripts-banner) so it can _virtually_ exist on your site

Thank you for your contributions :)
